# SwiftLint Configuration
# flutter_fast_starterのanalysis_options.yamlの方針をSwift向けに移植
# Run: swiftlint / swiftlint --fix

# 解析対象
included:
  - OldIPhoneCameraExperience
  - OldIPhoneCameraExperienceTests

# 除外対象（自動生成ファイル・リソース等）
excluded:
  - OldIPhoneCameraExperience/Preview Content
  - "**/*.generated.swift"

# ============================================
# 型安全性の強化
# ============================================
# force_cast: 強制キャスト（as!）を禁止
# force_unwrapping: 強制アンラップ（!）を禁止
# force_try: 強制try（try!）を禁止

# ============================================
# コード構造・可読性
# ============================================
# line_length: 行の長さ制限
# function_body_length: メソッドの長さ制限（セルフレビュー基準: 40行）
# nesting: ネストの深さ制限（セルフレビュー基準: 2重以内）
# file_length: ファイルの長さ制限
# type_body_length: 型のボディ長さ制限

# ============================================
# イミュータビリティ推奨
# ============================================
# prefer_let: var より let を推奨

# ============================================
# エラー防止
# ============================================
# empty_catch: 空catchブロックを禁止
# print_usage: print文の使用を警告

opt_in_rules:
  - force_unwrapping
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

disabled_rules: []

# ============================================
# ルール設定
# ============================================

# 行の長さ: 警告120文字、エラー200文字
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

# メソッドの長さ: 警告40行、エラー60行（セルフレビュー基準準拠）
function_body_length:
  warning: 40
  error: 60

# ファイルの長さ: 警告400行、エラー600行
file_length:
  warning: 400
  error: 600

# 型のボディ長さ: 警告300行、エラー500行
type_body_length:
  warning: 300
  error: 500

# ネストの深さ: type 2重、function 2重（セルフレビュー基準準拠）
nesting:
  type_level: 2
  function_level: 2

# 関数のパラメータ数: 警告5個、エラー8個
function_parameter_count:
  warning: 5
  error: 8

# Cyclomatic Complexity: 警告10、エラー20
cyclomatic_complexity:
  warning: 10
  error: 20

# 識別子の長さ
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - to

# 型名の長さ
type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 50
    error: 60
